### PR TITLE
Support environment deletion through API

### PR DESCRIPTION
**Pull request by ayalash**

### CODE REVIEW

**Comment by ayalash** [comment]
I marked this PR as draft, until I'll fix the DB notification error that I gets (the deletion succeed):
```
[2023-08-01T14:50:12Z INFO  actix_web::middleware::logger] 127.0.0.1 "DELETE /api/v2/envs/02d007c2-f24b-44a4-8200-0b0264f05d53 HTTP/1.1" 204 0 "-" "platz-sdk/0.5.1/lib" 0.016567
[2023-08-01T14:50:12Z ERROR platz_db::events] Error listening for notifications: EventBroadcastError(SendError(DbEvent { operation: Delete, table: Envs, data: DbEventData { id: 02d007c2-f24b-44a4-8200-0b0264f05d53 } }))
```

**Comment by ayalash** [comment]
The `EventBroadcastError(SendError(..))` log was emitted because I run from my laptop and there were no listeners.

**Comment by ayalash** [comment]
@popen2 As far as I understand, the `SendError` returns where there are no listeners. Do we want to the log message & level to be more indicative?

**Comment by popen2** [comment]
> @popen2 As far as I understand, the `SendError` returns where there are no listeners. Do we want to the log message & level to be more indicative?

Yeah, it makes sense to improve the logging in that area, but since it's not related to this PR I'll go ahead and merge it.

Thanks!

**Pull request merged**
